---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-namespace-issue
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/M0NsTeRRR/argocd-namespace-issue
      revision: HEAD
      directories:
      - path: argocd/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/M0NsTeRRR/argocd-namespace-issue
        targetRevision: HEAD
        path: '{{.path.path}}'
        kustomize:
          namespace: '{{.path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true